name       : sdl1-image
version    : 1.2.12
release    : 1
source     :
    - https://www.libsdl.org/projects/SDL_image/release/SDL_image-1.2.12.tar.gz : 0b90722984561004de84847744d566809dbb9daf732a9e503b91a1b5a84e5699
license    : Zlib
summary    : SDL_image is an image file loading library.
description: |
    SDL_image is an image file loading library.
builddeps  :
    - pkgconfig(sdl)
    - pkgconfig(libtiff-4)
    - pkgconfig(libpng)
    - pkgconfig(libwebp)
    - libjpeg-turbo-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
