name       : sdl1-image
version    : 1.2.12
release    : 3
source     :
    - https://www.libsdl.org/projects/SDL_image/release/SDL_image-1.2.12.tar.gz : 0b90722984561004de84847744d566809dbb9daf732a9e503b91a1b5a84e5699
license    : Zlib
component  : multimedia.library
summary    : SDL_image is an image file loading library.
description: |
    SDL_image is an image file loading library.
builddeps  :
    - sdl1-devel
    - sdl1-32bit-devel
    - pkgconfig(libtiff-4)
    - pkgconfig32(libtiff-4)
    - pkgconfig(libpng)
    - pkgconfig32(libpng)
    - pkgconfig(libwebp)
    - pkgconfig32(libwebp)
    - libjpeg-turbo-devel
    - libjpeg-turbo-32bit-devel
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32     : yes
optimize   : speed
setup      : |
    %configure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
